### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by OlsenDK04** [wrefgtzweve/SpaceEngineersDLCUnlocker#21]
When I Start the game there goes about 5 seconds and then it crashes.
[SpaceEngineers_20230418_23024400.log](https://github.com/wrefgtzweve/SpaceEngineersDLCUnlocker/files/11266352/SpaceEngineers_20230418_23024400.log)

**Comment by wrefgtzweve** [comment]
```
2023-04-18 23:02:51.952 - Thread:   1 ->  Exception occurred: System.IO.FileNotFoundException: Could not load file or assembly 'file:///D:\SteamLibrary\steamapps\workshop\content\244850\2407984968\RunPluginLoader' or one of its dependencies. The system cannot find the file specified.
File name: 'file:///D:\SteamLibrary\steamapps\workshop\content\244850\2407984968\RunPluginLoader'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at VRage.Plugins.MyPlugins.RegisterFromArgs(String[] args)
   at Sandbox.MySandboxGame.RegisterAssemblies(String[] args)
   at Sandbox.MySandboxGame..ctor(String[] commandlineArgs, IntPtr windowHandle)
   at SpaceEngineers.Game.SpaceEngineersGame..ctor(String[] commandlineArgs)
   at SpaceEngineers.MyProgram.Main(String[] args)
```

Doesn't seem to have anything to do with the dlc unlocker, the dlc unlocker cant cause errors like this as its just xml editing.

Your issue comes from: https://steamcommunity.com/sharedfiles/filedetails/?id=2407984968 try uninstalling or message the author of that addon. Seems like that addon is deprecated though, so you might have to get the new version.

**Comment by wrefgtzweve** [comment]
Closing this as there was no further response
